//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenDB.Analyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RavenDB.Analyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RavenDB will return 128 items by default - use Skip() and Take() to handle this issue. Or consider using another API..
        /// </summary>
        internal static string AnalyzerDescriptionRDB1001 {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionRDB1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RavenDB will return at most 1024 items by default for each Take(). Use Skip() and Take() to enumerate entire collection..
        /// </summary>
        internal static string AnalyzerDescriptionRDB1002 {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionRDB1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing use of Take() when using RavenDB query API.
        /// </summary>
        internal static string AnalyzerMessageFormatRDB1001 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatRDB1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take() with n &gt; 1024 when using RavenDB query API.
        /// </summary>
        internal static string AnalyzerMessageFormatRDB1002 {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatRDB1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing use of Take().
        /// </summary>
        internal static string AnalyzerTitleRDB1001 {
            get {
                return ResourceManager.GetString("AnalyzerTitleRDB1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take() n &gt; 1024.
        /// </summary>
        internal static string AnalyzerTitleRDB1002 {
            get {
                return ResourceManager.GetString("AnalyzerTitleRDB1002", resourceCulture);
            }
        }
    }
}
